### ISSUE TITLE
Lost ability to set index template since version 2.0.0

### ISSUE THREAD

**Issue by r-tock** [allegro/embedded-elasticsearch#11]
it was called putTemplate() in 1.0.0 I cannot find the equivalent for the new version

**Comment by gaczm** [comment]
There was no such function in embedded-elasticsearch. Maybe you was doing so using transport client created by `createClient` method? Could you show some code example?

**Comment by r-tock** [comment]
Hmm yeah. you are right. what is the way to do that with the new client
```diff
-      IndicesAdminClient indices = elasticsearchServer.createClient().admin().indices();
-      indices.preparePutTemplate("*-entity-*")
-          .setSource(Resources.toString(Resources.getResource("entity_index_template.json"), Charsets.UTF_8))
-          .get();
```

**Comment by gaczm** [comment]
You can easily create transport client by yourself. You have all needed data to do so :)

Since version 2.0.0 we got rid off elasticsearch dependency. By doing so, we are able to support both 2.x and 5.x versions of elasticsearch (and soon there will be also support for 1.x #12). We also don't introduce transitive dependency with elasticsearch into users projects. But we also lost `createClient` method, but personally I don't consider this a great loss, cause as I said you can easliy create transport client if you need it (and often it is not needed at all)

**Comment by r-tock** [comment]
right, unfortunately I was attempting a skew tests run 2.3.3 as server with 5.0.0 as client and hoping that I can somehow set the index template on the server. But it looks like there are connectivity issues with such a skew. I really hate that elastic search major version bumps require cluster wide restarts. It's a pain in the ass for SREs and SWEs. 😢
